### ISSUE TITLE
Question: Non-avatar Players

### ISSUE THREAD

**Issue by Haxley** [linuzo/XBL_PlayerList#1]
Most people in the player list have an avatar but some don't. Does that mean they're not connected to XBL and using some crack or does it mean they don't have an avatar set or something?

**Comment by DegenApeDev** [comment]
I believe that has to do with the player permissions if they choose to share the avatar with their friends or not. Also it could be because they were on the server before you joined and it didn't update your list yet. Since this plugin does each task on join it will only show those that join after you. However the people that joined before you can see your profile so they could add you either way.
